# Generated by Django 5.2.12 on 2026-03-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=25)),
                ('height_cm', models.DecimalField(decimal_places=2, default=170, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('activity_level', models.CharField(choices=[('low', 'Niska aktywność'), ('moderate', 'Średnia aktywność'), ('high', 'Wysoka aktywność')], default='moderate', max_length=20)),
                ('goal', models.CharField(choices=[('cut', 'Redukcja'), ('maintain', 'Utrzymanie'), ('bulk', 'Masa')], default='maintain', max_length=20)),
                ('daily_calorie_limit', models.PositiveIntegerField(default=2200)),
                ('daily_protein_limit', models.PositiveIntegerField(default=120)),
                ('daily_fat_limit', models.PositiveIntegerField(default=70)),
                ('daily_carbs_limit', models.PositiveIntegerField(default=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
