# Generated by Django 5.2.12 on 2026-03-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('vegetables', 'Warzywa'), ('fruit', 'Owoce'), ('dairy', 'Nabiał'), ('meat', 'Mięso'), ('grains', 'Produkty zbożowe'), ('dry', 'Produkty suche'), ('other', 'Inne')], default='other', max_length=20)),
                ('default_unit', models.CharField(default='g', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Meal categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('calories', models.DecimalField(decimal_places=2, help_text='Na 1 porcję', max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Na 1 porcję', max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Na 1 porcję', max_digits=7)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Na 1 porcję', max_digits=7)),
                ('servings', models.PositiveIntegerField(default=1, help_text='Liczba porcji w przepisie')),
                ('diet_type', models.CharField(choices=[('standard', 'Standard'), ('vegetarian', 'Wegetariańskie'), ('vegan', 'Wegańskie'), ('gluten_free', 'Bez glutenu'), ('lactose_free', 'Bez laktozy')], default='standard', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='meals.mealcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_meals', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='meals.meal')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'meal')},
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='g', max_length=30)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_meals', to='meals.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='meals.meal')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('meal', 'ingredient')},
            },
        ),
    ]
