# Generated by Django 5.2.14 on 2026-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='preferred_meal_time',
            field=models.CharField(choices=[('any', 'Dowolna pora'), ('breakfast', 'Śniadanie'), ('lunch', 'Lunch'), ('dinner', 'Obiad'), ('snack', 'Przekąska'), ('supper', 'Kolacja')], default='any', max_length=20),
        ),
    ]
