# Generated by Django 5.2.14 on 2026-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_preferred_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='preferred_meal_time',
            field=models.CharField(default='any', help_text='Mozesz wybrac kilka por posilku.', max_length=120),
        ),
    ]
