# Generated by Django 5.2.14 on 2026-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_preferred_meal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.DeleteModel(
            name='MealCategory',
        ),
    ]
