# Generated by Django 5.2.12 on 2026-03-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=150)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='g', max_length=30)),
                ('category', models.CharField(choices=[('vegetables', 'Warzywa'), ('fruit', 'Owoce'), ('dairy', 'Nabiał'), ('meat', 'Mięso'), ('grains', 'Produkty zbożowe'), ('dry', 'Produkty suche'), ('other', 'Inne')], default='other', max_length=20)),
                ('is_checked', models.BooleanField(default=False)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['category', 'ingredient_name'],
            },
        ),
    ]
