# Generated by Django 5.2.12 on 2026-03-30 17:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Śniadanie'), ('lunch', 'Lunch'), ('dinner', 'Obiad'), ('snack', 'Przekąska'), ('supper', 'Kolacja')], default='breakfast', max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='planner.dailyplan')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_entries', to='meals.meal')),
            ],
            options={
                'ordering': ['meal_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('calorie_target', models.PositiveIntegerField(default=2000)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplateMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Śniadanie'), ('lunch', 'Lunch'), ('dinner', 'Obiad'), ('snack', 'Przekąska'), ('supper', 'Kolacja')], default='breakfast', max_length=20)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_meals', to='planner.plantemplate')),
            ],
            options={
                'ordering': ['meal_time', 'id'],
            },
        ),
    ]
